### ISSUE TITLE
Not an issue just a recomendation

### ISSUE THREAD

**Issue by ZLCube** [OusH4ck/NetSnoopSpoof#1]
Maybe you could replace the hard coded IP targets by passing an input or sys.argv since you are already importing the sys librarie.
Current:
gateway_ip = "192.168.1.1"   # Gateway's IP
target_ip = "192.168.1.221"  # Victim's IP

Suggested
gateway_ip = sys.argv[1]      # Gateway's IP
target_ip = sys.argv[2]         # Victim's IP

Or
gateway_ip = input('Gateway's IP: ')  
target_ip = nput(Victim's IP: '')

**Comment by OusH4ck** [comment]
@ZLCube Oh thanks, I'll do it soon!
